### PR TITLE
Bump to 2.6.1

### PR DESCRIPTION
**Pull request by tomvothecoder**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by chengzhuzhang — APPROVED** [review]
Look good to me!

**Comment by tomvothecoder** [comment]
Thanks @chengzhuzhang, the build is passing so I will go ahead and merge.

**Comment by xylar** [comment]
@tomvothecoder and @chengzhuzhang, it probably didn't matter this time but it is always a good idea to rerender the feedstock before you merge.  Just follow the instruction of the item you didn't check above (put `@conda-forge-admin, please rerender` in a comment).

This will make sure any changes that conda-forge itself manages get incorporated.

**Comment by tomvothecoder** [comment]
Thanks for the info @xylar. I ran that command in another feedstock PR and it said something like "nothing to do", so I was under the impression that you only run it if there are changes to the PR.

I now see that it is also a way to validate that the package builds before merging.

**Comment by xylar** [comment]
> I now see that it is also a way to validate that the package builds before merging.

I guess that's right in a certain sense.  There's a software called `conda-smithy` that keeps track of updates to all of the feedstocks.  It has total control of everything outside of the `recipe` directory and the `conda_forge.yaml` file.  You aren't supposed to change anything outside of those two.  When you rerender, you let `conda-smithy` update all the other files.  Sometimes, that's based on changes you made to the recipe (e.g. adding new dependencies that are pinned to specific versions on conda-forge, like `hdf5`).  Sometimes, it's updates to things like the docker images it uses, the access tokens to the CI services, and who knows what else.  Basically, you never know what you're going to get until you do the rerender.

You **can** rerender locally but I don't really recommend it.  It's easier to let the bot take care of it with the comment I mentioned above.

**Pull request merged**
