### PR TITLE
DEV: Update to v2.5.0rc1

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@chengzhuzhang and @forsyth2, FYI, this is how you do a dev build on conda-forge.  You point to a target channel that is `conda-forge` and a label (in this case, I picked `e3sm_dev` so I can use that label for MPAS-Analysis, too.).

**Comment by xylar** [comment]
@forsyth2 and @chengzhuzhang, the tests are failing.  Did they work for you?  Do they need to be updated somehow here?

**Comment by xylar** [comment]
I did a local run of your tests.  I think expecting pixel-exact reprodocability of figures is not going to be a sustainable thing.  That requires exactly the same versions of all the libraries, notably matplotlib.  I think we need to chat about this.

If this is a feature you really want, you need to pin matplotlib in your conda recipe to the version in your dev environment and we need to agree on a matching pin for matplotlib in E3SM-Unified.  I'm personally not in favor of doing that because it places a pretty heavy restriction the other packages, which may wish to always use the latest matplotlib.

An alternative is that you keep update your development environment and regenerate your cached files every time matplotlib gets updated.  This might be a feasible option, but someone will need to be watching the [matplotlib-feedstock](https://github.com/conda-forge/matplotlib-feedstock) for new releases so you stay in sync.

Another alternative is that these image tests are only used for your development and you provide a way for them to be turned off when testing e3sm_diags here.

**Comment by xylar** [comment]
This works if I pin `matplotlib-base` to the older 3.3.4 version used in the `e3sm_diags` dev. environment.  As I stated above, that's not my preferred solution but let me know how you would prefer to proceed.

**Comment by xylar** [comment]
I think I'm going to stick with the `matplotlib` pin for this release candidate.  Hopefully, we can relax this constraint somehow in an `rc2` later this month.

**Comment by forsyth2** [comment]
> I did a local run of your tests. I think expecting pixel-exact reprodocability of figures is not going to be a sustainable thing. That requires exactly the same versions of all the libraries, notably matplotlib. I think we need to chat about this.

I do have a "within-epsilon"  of exact replica. Is the issue just that the epsilon value should be higher? Do versions of `matplotlib` to differ so significantly that a user would be able to visually tell the difference between plots generated with different versions?


> An alternative is that you keep update your development environment and regenerate your cached files every time matplotlib gets updated. This might be a feasible option, but someone will need to be watching the [matplotlib-feedstock](https://github.com/conda-forge/matplotlib-feedstock) for new releases so you stay in sync.
> 
> Another alternative is that these image tests are only used for your development and you provide a way for them to be turned off when testing e3sm_diags here.

@chengzhuzhang I think either of those alternatives  (updating expected images for each `matplotlib` version OR only using those tests for development) sound good. Do you have a preference?

**Comment by chengzhuzhang** [comment]
Thanks for bringing this up, Xylar. We didn't consider the effect of changing `matploblit` version to the image checker at the beginning. And this actually provide another reason, why we need this sort of tests. It is useful to keep them.

I agree with @forsyth2, we should first identify from our end if an matplotlib update will change our results. (i.g., unexpected changes in plots). Ryan, would you help manually compare the plots generated with two matplotlibs versions, and we can figure out how to proceed forward with this test?

**Comment by forsyth2** [comment]
@chengzhuzhang Yes, I'll test with different versions and check if I can see a difference in the plots.

This reminds me, we should probably make a v2.5.0 tutorial (https://github.com/E3SM-Project/e3sm_diags/issues/459). Luckily, that's in the `examples/tutorial` directory, so it doesn't need to be included in the actual release. However, it would be a good idea to have the new diags highlighted in that tutorial by July 1.

**Comment by xylar** [comment]
> I do have a "within-epsilon" of exact replica. Is the issue just that the epsilon value should be higher? Do versions of matplotlib to differ so significantly that a user would be able to visually tell the difference between plots generated with different versions?

Yes, font spacing can change and things like that.  So an epsilon isn't going to take care of this.

> Yes, I'll test with different versions and check if I can see a difference in the plots.

I ran locally and could visually see the differences.  Fonts were visibly crisper in the new version .  Bigger changes wouldn't be surprising, even with a micro version change in matplotlib.  These things just aren't expected or guaranteed to be stable.

Please make a release candidate (rc2) sometime in the next week or so that supports the latest matplotlib, however you decide to handle this.

**Comment by forsyth2** [comment]
@xylar Ah, that makes sense. Thanks for the explanation.

@chengzhuzhang I think we should just update the expected images (for both `test_diags.py` which is included in the CI/CD tests and `complete_run.py` which is not) for every `matplotlib` update. We'd need to do that anyway for the tests to work for developers.

I can update the `conda` environments to use the latest version of `matplotlib` (looks like that's `3.4.2`) and generate new expected images.

**Comment by chengzhuzhang** [comment]
Hi @forsyth2 If we can verify only fonts/spacing etc. are changed, between 3.3.4 and 3.4.2, I would propose to generate a patch here for the feedstock to turn off the image checker. We just need the checker in development and updating expected figures (and manually compare figures over each matplotlib versions is too much work and against the motivation of automating image checking). What we can do is to update expected figures each time when we release with `e3sm-unified`, which requires the latest `matplotlib`. 

I found this example for patching (https://github.com/conda-forge/e3sm_diags-feedstock/commit/4db527dfce8751e6f979ead367e684b5a7542492), would you help apply one for turn off image checker?

**Comment by xylar** [comment]
@chengzhuzhang, I think that should like the best approach.  The problem with having test images for the latest matplotlib is that it means test only work with one specific version of matplotlib.  For example, when matplotlib got updated, the tests for v2.4.0 stopped working.  We currently can't rebuild that version even if we want to because of the failing tests.  The same would happen the next time matplotlib gets updated even if you generate images with 3.4.2 now.  So I think these test are only safe to use internally, where you are pinning a specific matplotlib version for your development, not on conda-forge.

**Comment by forsyth2** [comment]
@chengzhuzhang @xylar Sure I can do that. So, it looks like I just need to copy the output of a `git diff` into a `patch` file? Do the subject line or the `2.29.2` in that patch example do anything or are those just comments?

**Comment by xylar** [comment]
> Sure I can do that. So, it looks like I just need to copy the output of a git diff into a patch file?

Yes, that works.  If it's more convenient, you can create 2 directories, one with the original source and one with the modified version.  Then run:
```
diff -ruN original patched > recipe/0001-my-fix.patch
```
where `original` and `patched` are before and after the change you want to make, respectively.  This approach is handy if you want a single patch that would involve multiple git commits or if you don't have a git commit for the change you want to patch.

> Do the subject line or the 2.29.2 in that patch example do anything or are those just comments?

No idea about the 2.29.2 but the subject doesn't matter.

Here are some tips:
https://stackoverflow.com/a/6658352/7728169

https://stackoverflow.com/a/9982282/7728169

**Pull request merged**
