### PR TITLE
[ci skip] adding user @tomvothecoder

### LINKED ISSUE #12: @conda-forge-admin, please add user @tomvothecoder

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added user @tomvothecoder as instructed in #12.

Merge this PR to add the user. Please do not rerender this PR or change it in any way. It has `[ci skip]` in the commit message to avoid pushing a new build and so the build configuration in the feedstock should not be changed.

Please contact [conda-forge/core](https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-contact-core) to have this PR merged, if the maintainer is unresponsive.

Fixes #12

### CODE REVIEW

**Comment by tomvothecoder** [comment]
I noticed the building is failing. I'm not familiar with Azure Pipelines, but I'll try to debug.

There are several `subprocess.CalledProcessError` tracebacks, which might be related to updating how integration tests are called in (from implicit paths to explicit paths) in https://github.com/E3SM-Project/e3sm_diags/pull/546.

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1642524810317/test_tmp/tests/integration/test_diags.py", line 137, in setUpClass
    subprocess.check_output(command.split()).decode("utf-8").splitlines()
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1642524810317/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1642524810317/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'all_sets.py', '-d', 'all_sets.cfg']' returned non-zero exit status 1.
```

There is also an `AttributeError` 
```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1642524810317/test_tmp/tests/integration/test_run.py", line 67, in test_all_sets_and_all_seasons
    parameters = self.runner.get_final_parameters(
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1642524810317/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/e3sm_diags/run.py", line 66, in get_final_parameters
    params = self.parser.get_parameters(
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1642524810317/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/cdp/cdp_parser.py", line 532, in get_parameters
    final_parameters = self.granulate(final_parameters)
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1642524810317/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/cdp/cdp_parser.py", line 410, in granulate
    if not isinstance(param_v, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'
```

**Comment by tomvothecoder** [comment]
> I noticed the building is failing. I'm not familiar with Azure Pipelines, but I'll try to debug.
> 
> There are several subprocess.CalledProcessError tracebacks, which might be related to updating how integration tests are called in (from implicit paths to explicit paths) in E3SM-Project/e3sm_diags#546.

Actually, I don't think that e3sm_diags PR should affect the build for this PR because the `meta.yaml` is still on v2.6.0?

https://github.com/conda-forge/e3sm_diags-feedstock/blob/a907d3403d41ac07e67353371b3a4065aa75882c/recipe/meta.yaml#L1-L10

**Comment by xylar** [comment]
@tomvothecoder, this can presumably only be caused by changes in the dependencies since the last (successful) built of 2.6.0.  I'll also look into it as soon as I have time.  But it looks like we'll need to bump the build number here.  Adding you without bumping only works if everything goes smoothly without any other changes.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@tomvothecoder, @chengzhuzhang and @forsyth2, all of the errors we're seeing here are related to the `cdp` package from CDAT.  I suspect it isn't being maintained well and isn't compatible with the latest python.  That's not a great situation for us to be in.  Any thoughts?

One option would be to constrain python <= 3.9 and see if that helps.  That's gets a big frowny face from me but it might be the only way forward if we want to use `cdp` and it isn't being maintained.  (And that's assuming that fix even helps.)  In any case, the fix would likely be needed in the `cdp` feedstock rather than here.  (Or perhaps both places.)

**Comment by xylar** [comment]
I'm testing a patch of `cdp` on my laptop.  I'll make a PR if it works.

**Comment by xylar** [comment]
See https://github.com/conda-forge/cdp-feedstock/pull/9

**Comment by xylar** [comment]
The `cdp` fix definitely helped but I'm still seeing this unrelated error:
```
Traceback (most recent call last):
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/e3sm_diags/e3sm_diags_driver.py", line 277, in run_diag
    single_result = module.run_diag(parameters)  # type: ignore
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/e3sm_diags/driver/arm_diags_driver.py", line 431, in run_diag
    return run_diag_convection_onset(parameter)
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/e3sm_diags/driver/arm_diags_driver.py", line 409, in run_diag_convection_onset
    arm_diags_plot.plot_convection_onset_statistics(
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/e3sm_diags/plot/cartopy/arm_diags_plot.py", line 160, in plot_convection_onset_statistics
    ax1.errorbar(
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 3467, in errorbar
    barcols.append(lines_func(
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 1063, in hlines
    minx = min(xmin.min(), xmax.min())
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/numpy/ma/core.py", line 5703, in min
    result = self.filled(fill_value).min(
  File "/home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: '<=' not supported between instances of 'float' and 'str'
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
........F........./home/xylar/miniconda3/conda-bld/e3sm_diags_1642533276894/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/cdp/cdp_parser.py:192: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(cfg_file_obj)
```

**Comment by tomvothecoder** [comment]
Thanks for working on the `cdp` patch. I'm unfamiliar with `cdp` so I don't have much to contribute there.

I'm not sure if maintaining the `cdp` dependencies falls under @jasonb5's role since it is apart of CDAT. In any case, this package (and the other CDAT dependencies) will eventually be deprecated this year (hopefully).

**Comment by xylar** [comment]
@tomvothecoder, we seem to be set as far `cdp` is concerned.

I'm trying to figure out the one remaining error, which is unrelated to `cdp`.

**Pull request closed without merging**
