### PR TITLE
Patch to skip image comparison

### PR DESCRIPTION
**Pull request by forsyth2**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Add patch to skip image comparison in the tests. As discussed in #4, using a different `matploblib` version can cause enough differences in the plots to cause tests to fail. This patch disables the image comparison part of the tests by default.

The code changes are based on https://github.com/conda-forge/e3sm_diags-feedstock/commit/4db527dfce8751e6f979ead367e684b5a7542492.

### CODE REVIEW

**Comment by forsyth2** [comment]
@xylar @chengzhuzhang This is ready for review. I'm assuming I also need to create a pull request to E3SM Diags with this patch's changes and then release `rc2`?

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@forsyth2, yes, please make an equivalent PR to the `dev` branch.  In that case, too, we will need to bump the build number and rerender the feedstock like I have done here.  I can do it there, too, if you prefer.

**Review by xylar — APPROVED** [review]
This patch looks good to me as long as the tests pass, I'll merge.

**Comment by forsyth2** [comment]
> @forsyth2, yes, please make an equivalent PR to the `dev` branch. In that case, too, we will need to bump the build number and rerender the feedstock like I have done here. I can do it there, too, if you prefer.

I was going to make two commits to E3SM Diags -- one with the patch's changes and one to change the version numbers to include `rc2`. Should it all be packaged together in one commit?

**Comment by xylar** [comment]
@forsyth2, the patch needs to be renamed.  It is called `comarsion`, not `comparison` (a kind typo I make all the time!).

**Comment by xylar** [comment]
> I was going to make two commits to E3SM Diags -- one with the patch's changes and one to change the version numbers to include rc2. Should it all be packaged together in one commit?

Oh, okay.  That's great!  If you make `rc2`, then, I'll take care of a PR to the `dev` branch here.

**Comment by forsyth2** [comment]
> @forsyth2, the patch needs to be renamed. It is called `comarsion`, not `comparison` (a kind typo I make all the time!).

Thanks for catching that! Should I just push another commit changing that? Does anything else (e.g., build number) need to change with that?

> Oh, okay. That's great! If you make `rc2`, then, I'll take care of a PR to the `dev` branch here.

Sounds good, thanks!

**Comment by xylar** [comment]
> Thanks for catching that! Should I just push another commit changing that? Does anything else (e.g., build number) need to change with that?

Yes, just fetch my changes, do a hard reset, and push another commit to rename the patch file.  No need to bump the build number.  A new build doesn't get created until we merge this PR.  You would only need to bump the build number if you make a new PR after this one.

**Comment by chengzhuzhang** [comment]
Hey @xylar is it okay to just turn off image checker here while leave it on for `e3sm-diags` repo?

**Comment by xylar** [comment]
@chengzhuzhang, yes, that's fine.  This is the "official" place that 2.4.0 gets built so there's nowhere else that needs to be patched.  And no need for a 2.4.1 bug fix or anything like that.  We patch conda-forge packages in this way fairly often.

**Comment by chengzhuzhang** [comment]
Thank you, Xylar!

**Comment by forsyth2** [comment]
> Yes, just fetch my changes, do a hard reset, and push another commit to rename the patch file.

Ok commit added!

> This is the "official" place that 2.4.0 gets built so there's nowhere else that needs to be patched. And no need for a 2.4.1 bug fix or anything like that.

Sounds good, so no need to create a `rc2` release then?

**Comment by xylar** [comment]
> Sounds good, so no need to create a rc2 release then?

Sorry for the confusion.  Yes, I think your plan to create 2.5.0rc2 is a good one.  If you don't want to, we would need to patch 2.5.0rc1, but that is kind of sloppy.  So your idea was better.

This was just a discussion about 2.4.0.  No need to do any updates for *that* release in the `E3SM-Project/e3sm_diags` repo.  It has been taken care of here.

Does that clear things up?

**Pull request merged**
