### PR TITLE
Patch 1 for v2.12.1 with `scipy` dependency

### PR DESCRIPTION
**Pull request by tomvothecoder**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- Related to https://github.com/E3SM-Project/e3sm_diags/issues/904
- Upstream fix: https://github.com/E3SM-Project/e3sm_diags/pull/905

### CODE REVIEW

**Comment by tomvothecoder** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@tomvothecoder, ideally, you would fix this in the main repo first and then here, pointing to the "upstream" fix.

**Comment by xylar** [comment]
scipy is in both the ci and dev environments but it seems to be incorrectly listed under testing.

**Comment by xylar** [comment]
scipy should be removed from test here since it is now in run.

**Comment by tomvothecoder** [comment]
> @tomvothecoder, ideally, you would fix this in the main repo first and then here, pointing to the "upstream" fix.
> scipy is in both the ci and dev environments but it seems to be incorrectly listed under testing.

@xylar Yup just opened https://github.com/E3SM-Project/e3sm_diags/pull/905. 

> scipy should be removed from test here since it is now in run.

Thanks, just removed.

**Review by tomvothecoder — COMMENTED** [review]
@xylar let me know how this PR looks.

I will merge the [upstream fix](https://github.com/E3SM-Project/e3sm_diags/pull/905) first before merging this PR.

**Review by xylar — APPROVED** [review]
Looks good.

**Pull request merged**
