### PR TITLE
Update to 2.6.0rc1

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@tomvothecoder, if you have any comments, they would be welcome.

**Comment by xylar** [comment]
I think this is failing because of:
https://github.com/conda-forge/cdms2-feedstock/pull/75
`libcdms` recently migrated to `jasper` v2:
https://github.com/conda-forge/libcdms-feedstock/pull/41
But `cmds2` didn't list `jasper` as a dependency.  This meant that it got built with `jasper` v1 but is trying to run with `japser` v2 coming from `libcdms2`, and this is failing.

**Comment by xylar** [comment]
We probably do want `jasper` v2, so we'll probably want to wait for https://github.com/conda-forge/cdtime-feedstock/pull/49 and  https://github.com/conda-forge/cdms2-feedstock/pull/76

**Comment by xylar** [comment]
This has really opened up a can of worms!  CDAT feedstocks were not handling `jasper` correctly.

**Comment by xylar** [comment]
The CDAT can of worms was bigger than I realized.  `libdrs_f` had also not been migrated to the latest `libnetcdf`.  I took care of that.  I also played around a little with cross-compilation for newer architectures, which caused another headache.  (It's something I wanted to learn about generally and this was just a test bed.)

Anyway, I think all the dependencies *should* be in place now.

**Comment by tomvothecoder** [comment]
@xylar Thanks for going down the rabbithole of fixing the CDAT dependencies and getting this merged! CDAT + dependency issues, name a better duo.

**Comment by xylar** [comment]
I don't mind too much and it's something I do for a lot of different packages.  But this was a tough case!  Just glad it's solved...

**Comment by chengzhuzhang** [comment]
This is awesome. Thank you @xylar  and @tomvothecoder!

**Pull request merged**
