### PR TITLE
Fix issue with error bars

### LINKED ISSUE #12: @conda-forge-admin, please add user @tomvothecoder

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #13 
closes #12

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Fingers crossed🤞🏻

**Comment by xylar** [comment]
Nope, this fix doesn't work.  Switching to draft mode.

**Comment by xylar** [comment]
@chengzhuzhang, the fix did, indeed, work.  Please merge if you're happy.

**Comment by chengzhuzhang** [comment]
Thanks a lot. Merging.

**Pull request merged**
